git:
  quiet: true
language: node_js
node_js:
  - lts/*
env:
- NODE_ENV=development
before_install:
- npm i -g npm
install:
- npm install
stages:
  - lint
  - test
jobs:
  include:
  - stage: lint
    name: Lint TS
    script: npm run lint
  - name: Lint JS
    script: npm run lintJS
  - stage: test
    script: npm run test
